name: James J. Kim
tagline: MS in CS @ Cornell University
career-objective: | 
  I'm a [MS student](https://www.cs.cornell.edu/ms) in Computer Science at [Cornell](https://cs.cornell.edu/), broadly interested in building sample-efficient AI Agents to accelerate scientific discovery and streamline research workflows with Prof. [Jennifer Sun](https://jenjsun.com/).

  In a previous life, I developed computational models of brain-behavior dynamics in substance use addiction with Prof. Amy Kuceyeski in the [CoCo Lab](https://www.cocolaboratory.com/), and worked on real-time acoustic sensing for hand pose tracking in wearable tech with Prof. Cheng Zhang in the [SciFi Lab](https://www.scifilab.org/). 

  Feel free to reach outâ€” happy to chat!
color_theme: green # red or blue or green or else
avatar-filename: avatar.png
url: biojameskim.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: jjk297@cornell.edu
  github: 
    visibility: true
    handle: biojameskim
  linkedin: 
    visibility: true
    handle: biojameskim
  bearblog: 
    visibility: true
    handle: biojameskim

# Collections
collections:
  education:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: order
  research_experience:
    output: false
    sort_by: order
  teaching_experience:
    output: false
    sort_by: order
  work_experience:
    output: false
    sort_by: order
  skills:
    output: false
    sort_by: order

# About Page Options
collection_option:
  education: 
    label: Education
    visibility: true
  publications: 
    label: Publications
    visibility: true
  research_experience:
    label: Research Experience
    visibility: true
  teaching_experience:
    label: Teaching Experience
    visibility: true
  work_experience: 
    label: Work Experience
    visibility: true
  skills: 
    label: Technical Skills
    visibility: true

navigation:
- title: About
  url: /
- title: CV
  url: /files/cv.pdf
# - title: Blog
#   url: /blog/
- title: Contact
  url: /contact

include:
  - _pages

exclude:
  - readme.md
  - vendor        # ignore all gems installed in ./vendor/bundle

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Contact Form
formspree:
  endpoint: https://formspree.io/f/mqalbewz

# Google Analytics
google_analytics: G-7G7LJ1G4BK